### ISSUE TITLE
HelloWorld Test › deployed      connect ECONNREFUSED

### ISSUE THREAD

**Issue by rebekahkim** [oasislabs/tutorials#42]
**Description of the bug**
Service doesn't connect to oasis local chain

**Steps to reproduce**
1. `oasis test` in `app`
2.  See error

```
 FAIL  test/service.spec.ts
  HelloWorld Test
    ✕ deployed (4ms)
    ✕ known greeting (1ms)
    ✕ insert new greeting in Samoan

  ● HelloWorld Test › deployed

    connect ECONNREFUSED 127.0.0.1:80
```

**Expected behavior**
Service connects to chain

**Environment**
 - OS:  macOS Mojave

**Additional information**
`MD5 (/Users/Kim/.local/bin/oasis) = 5f790a1f60da0adbcfd5193dcf5e44c5`

`~/.config/oasis/config.toml` is:
```
[profile.default]
gateway = "https://gateway.devnet.oasiscloud.io"
credential = [redacted]

[profile.local]
gateway = "ws://localhost:8546"  # web3
credential = [redacted]
```

**Comment by sharmaster96** [comment]
This is caused by an internal configuration issue between version changes. The best (current) way to resolve this is to manually try from a clean start:

1) Uninstall oasis: `rm -rf ~/.local/share/oasis ~/.config/oasis ~/.local/bin/oasis* <path to tutorials repo>`.
2) Re-install oasis `curl --proto '=https' --tlsv1.2 -sSL https://get.oasis.dev | python` and re-clone tutorials `git clone https://github.com/oasislabs/tutorials`

An easier process for version updates / uninstall is in the works: https://github.com/oasislabs/oasis-cli/issues/116.
